package io.dongtai.iast.common.constants;

public class PropertyConstant {
    public static final String PROPERTY_DEBUG = "dongtai.debug";
    public static final String PROPERTY_APP_NAME = "dongtai.app.name";
    public static final String PROPERTY_APP_VERSION = "dongtai.app.version";
    public static final String PROPERTY_APP_TEMPLATE = "dongtai.app.template";
    public static final String PROPERTY_ENGINE_NAME = "dongtai.engine.name";
    public static final String PROPERTY_CLUSTER_NAME = "dongtai.cluster.name";
    public static final String PROPERTY_CLUSTER_VERSION = "dongtai.cluster.version";
    public static final String PROPERTY_SERVER_URL = "dongtai.server.url";
    public static final String PROPERTY_SERVER_TOKEN = "dongtai.server.token";
    public static final String PROPERTY_SERVER_PACKAGE = "dongtai.server.package";
    public static final String PROPERTY_LOG = "dongtai.log";
    public static final String PROPERTY_LOG_LEVEL = "dongtai.log.level";
    public static final String PROPERTY_LOG_PATH = "dongtai.log.path";
    public static final String PROPERTY_LOG_DISABLE_COLLECTOR = "dongtai.log.disable-collector";
    public static final String PROPERTY_ENGINE_DELAY_TIME = "iast.engine.delay.time";
    public static final String PROPERTY_PROXY_ENABLE = "iast.proxy.enable";
    public static final String PROPERTY_PROXY_HOST = "iast.proxy.host";
    public static final String PROPERTY_PROXY_PORT = "iast.proxy.port";
    public static final String PROPERTY_JAR_SPY_URL = "iast.jar.spy.url";
    public static final String PROPERTY_JAR_CORE_URL = "iast.jar.core.url";
    public static final String PROPERTY_JAR_API_URL = "iast.jar.api.url";
    public static final String PROPERTY_LOG_ADDRESS = "dongtai.log.address";
    public static final String PROPERTY_LOG_PORT = "dongtai.log.port";
    public static final String PROPERTY_DUMP_CLASS_PATH = "iast.dump.class.path";
    public static final String PROPERTY_DUMP_CLASS_ENABLE = "iast.dump.class.enable";
    public static final String PROPERTY_SERVICE_HEARTBEAT_INTERVAL = "iast.service.heartbeat.interval";
    public static final String PROPERTY_RESPONSE_LENGTH = "dongtai.response.length";
    public static final String PROPERTY_POLICY_PATH = "dongtai.policy.path";
    public static final String PROPERTY_UUID_PATH = "dongtai.uuid.path";
    public static final String PROPERTY_DISABLED_PLUGINS = "dongtai.disabled.plugins";
    public static final String PROPERTY_DISABLED_FEATURES = "dongtai.disabled.features";
    public static final String PROPERTY_TAINT_LENGTH = "dongtai.taint.length";
    public static final String PROPERTY_POOL_CAPACITY = "dongtai.pool.capacity";
    public static final String PROPERTY_POOL_SIZE = "dongtai.pool.size";
    public static final String PROPERTY_POOL_MAX_SIZE = "dongtai.pool.max.size";
    public static final String PROPERTY_POOL_KEEPALIVE = "dongtai.pool.keepalive";
}
